"""
mercado livre affiliate gateway.

fetches product offers directly from the ml public search api (no social list needed).
the user only needs to configure their ml affiliate client_id from the parceiros ml program.
affiliate links are generated by appending the client_id as a query parameter.

api used: https://api.mercadolibre.com/sites/MLB/search
(public api, no authentication required for product search)
"""

import logging
import re
import asyncio
import httpx
from datetime import datetime, timedelta
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ── category search terms for ml electronics ─────────────────────────────
ML_CATEGORY_MAP = {
    "notebook": {"query": "notebook", "label": "Notebooks", "category_id": "MLB1652"},
    "celular": {"query": "celular smartphone", "label": "Celulares", "category_id": "MLB1055"},
    "tablet": {"query": "tablet", "label": "Tablets", "category_id": "MLB1118"},
    "smart_tv": {"query": "smart tv 4k", "label": "Smart TVs", "category_id": "MLB1002"},
    "fone": {"query": "fone de ouvido bluetooth", "label": "Fones de Ouvido", "category_id": "MLB1051"},
    "ssd": {"query": "ssd nvme interno", "label": "SSDs", "category_id": "MLB1700"},
    "placa_video": {"query": "placa de video nvidia rtx", "label": "Placas de Vídeo", "category_id": "MLB1701"},
    "console": {"query": "console playstation xbox", "label": "Consoles", "category_id": "MLB1144"},
    "monitor": {"query": "monitor gamer 144hz", "label": "Monitores", "category_id": "MLB1006"},
    "mouse": {"query": "mouse gamer sem fio", "label": "Mouses Gamer", "category_id": "MLB1034"},
    "teclado": {"query": "teclado gamer mecanico", "label": "Teclados Gamer", "category_id": "MLB1033"},
    "impressora": {"query": "impressora multifuncional", "label": "Impressoras", "category_id": "MLB1009"},
}

ML_SEARCH_API = "https://api.mercadolibre.com/sites/MLB/search"

# affiliate link format: product link + client tracking params
ML_AFFILIATE_PARAMS = "matt_tool=affiliate&matt_word=&matt_source=&matt_campaign=&client_id={client_id}"


@dataclass
class MLOffer:
    title: str
    price: float
    old_price: float | None
    discount_percent: float
    image_url: str
    affiliate_link: str
    category: str
    installment_text: str = ""
    pix_discount_text: str = ""


# ── in-memory cache ───────────────────────────────────────────────────────
_ml_cache: dict[str, dict] = {}
CACHE_TTL_MINUTES = 60  # 1h cache — shorter than before since we use API now


class MercadoLivreGateway:
    """
    fetches electronics products directly from the ml public search api.
    no social list required — just the user's ml affiliate client_id.
    if no client_id is provided, links are still valid but not tracked.
    """

    def __init__(self, profile_slug: str = "", client_id: str = ""):
        """
        profile_slug: kept for backward compatibility (not used for fetching anymore).
        client_id: ml affiliate partner client id for tracked links.
                   get it at: parceiros.mercadolivre.com.br
        """
        self.profile_slug = profile_slug
        self.client_id = client_id.strip() if client_id else ""
        self.profile_url = f"https://www.mercadolivre.com.br/social/{profile_slug}/lists" if profile_slug else ""

    def _build_affiliate_link(self, product_url: str) -> str:
        """appends affiliate tracking params to a ml product url."""
        if not product_url:
            return product_url
        separator = "&" if "?" in product_url else "?"
        if self.client_id:
            params = ML_AFFILIATE_PARAMS.format(client_id=self.client_id)
            return f"{product_url}{separator}{params}"
        # no client_id: return clean link (not tracked but still works)
        return product_url

    async def get_offers(
        self,
        categories: list[str] | None = None,
        min_discount_percent: float = 5.0,
        max_offers: int = 5,
    ) -> list[MLOffer]:
        """
        returns affiliate offers from ml public search api.
        searches each requested category and returns the top discounted products.
        """
        if not categories:
            categories = ["notebook", "celular"]

        # build cache key per category set + client_id
        cache_key = f"{','.join(sorted(categories))}:{self.client_id}"
        now = datetime.utcnow()

        if cache_key in _ml_cache:
            cached = _ml_cache[cache_key]
            if cached["expires"] > now:
                logger.info("[ml] serving %d offers from cache", len(cached["offers"]))
                filtered = [o for o in cached["offers"] if o.discount_percent >= min_discount_percent]
                return filtered[:max_offers]

        # fetch fresh data from the ml search api
        all_offers: list[MLOffer] = []
        per_category = max(2, max_offers // max(len(categories), 1))

        tasks = [
            self._fetch_category(cat, per_category * 3)  # fetch more, filter later
            for cat in categories
            if cat in ML_CATEGORY_MAP
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        for result in results:
            if isinstance(result, list):
                all_offers.extend(result)
            elif isinstance(result, Exception):
                logger.warning("[ml] category fetch error: %s", result)

        # sort by discount descending, deduplicate by title
        all_offers.sort(key=lambda o: o.discount_percent, reverse=True)
        seen_titles: set[str] = set()
        unique_offers: list[MLOffer] = []
        for o in all_offers:
            key = o.title[:50].lower()
            if key not in seen_titles:
                seen_titles.add(key)
                unique_offers.append(o)

        # update cache
        _ml_cache[cache_key] = {
            "expires": now + timedelta(minutes=CACHE_TTL_MINUTES),
            "offers": unique_offers,
        }

        logger.info(
            "[ml] fetched %d total offers across %d categories (cached for %dmin)",
            len(unique_offers), len(categories), CACHE_TTL_MINUTES,
        )

        filtered = [o for o in unique_offers if o.discount_percent >= min_discount_percent]
        return filtered[:max_offers]

    async def _fetch_category(self, category_key: str, limit: int = 10) -> list[MLOffer]:
        """fetches products for a single category using the ml search api."""
        cat_info = ML_CATEGORY_MAP.get(category_key, {})
        query = cat_info.get("query", category_key)

        params = {
            "q": query,
            "sort": "relevance",
            "limit": min(limit, 50),
            "condition": "new",
            "shipping_cost": "free",  # prefer free shipping items
        }

        try:
            async with httpx.AsyncClient(timeout=20.0, follow_redirects=True) as client:
                resp = await client.get(
                    ML_SEARCH_API,
                    params=params,
                    headers={
                        "Accept": "application/json",
                        "Accept-Language": "pt-BR",
                        "User-Agent": "Mozilla/5.0 (compatible; WhatSellerPro/1.0)",
                    },
                )
                resp.raise_for_status()
                data = resp.json()
        except httpx.HTTPError as e:
            logger.error("[ml] http error for category %s: %s", category_key, e)
            return []
        except Exception as e:
            logger.error("[ml] unexpected error for category %s: %s", category_key, e)
            return []

        results = data.get("results", [])
        offers: list[MLOffer] = []

        for item in results:
            try:
                offer = self._parse_api_item(item, category_key)
                if offer:
                    offers.append(offer)
            except Exception as e:
                logger.debug("[ml] error parsing item: %s", e)

        logger.info("[ml] fetched %d offers for category '%s'", len(offers), category_key)
        return offers

    def _parse_api_item(self, item: dict, category_key: str) -> MLOffer | None:
        """parses a single ml api search result into an MLOffer."""
        title = item.get("title", "").strip()
        if not title or len(title) < 5:
            return None

        # prices
        price = float(item.get("price", 0) or 0)
        original_price = float(item.get("original_price") or 0)

        if price <= 0:
            return None

        # discount
        discount = 0.0
        if original_price and original_price > price:
            discount = round((1 - price / original_price) * 100, 1)

        # image: prefer first thumbnail, fallback to secure_thumbnail
        thumbnail = (
            item.get("thumbnail", "")
            .replace("http://", "https://")
            .replace("-I.jpg", "-O.jpg")  # request larger image variant
        )

        # product permalink (clean canonical url)
        permalink = item.get("permalink", "")

        # affiliate link
        affiliate_link = self._build_affiliate_link(permalink)

        # installments
        installment_text = ""
        installments = item.get("installments")
        if installments and isinstance(installments, dict):
            qty = installments.get("quantity")
            amount = installments.get("amount")
            rate = installments.get("rate", 0)
            if qty and amount:
                price_fmt = f"R$ {amount:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
                sem_juros = " sem juros" if rate == 0 else ""
                installment_text = f"{qty}x de {price_fmt}{sem_juros}"

        # truncate title
        if len(title) > 100:
            title = title[:97] + "..."

        return MLOffer(
            title=title,
            price=price,
            old_price=original_price if original_price > price else None,
            discount_percent=discount,
            image_url=thumbnail,
            affiliate_link=affiliate_link,
            category=category_key,
            installment_text=installment_text,
            pix_discount_text="",
        )

    @staticmethod
    def get_available_categories() -> dict[str, str]:
        """returns available category keys and labels."""
        return {k: v["label"] for k, v in ML_CATEGORY_MAP.items()}
