"""
mercado livre affiliate gateway.

fetches product offers from ml using two strategies:
1. public search api (primary) — fast but may return 403 from cloud IPs
2. web scraping of listado.mercadolivre.com.br (fallback) — parses __NEXT_DATA__ JSON

the user only needs to configure their ml affiliate client_id from the parceiros ml program.
affiliate links are generated by appending the client_id as a query parameter.
"""

import logging
import re
import json
import asyncio
import httpx
from bs4 import BeautifulSoup
from datetime import datetime, timedelta
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# ── category search terms for ml electronics ─────────────────────────────
ML_CATEGORY_MAP = {
    "notebook": {"query": "notebook", "label": "Notebooks", "category_id": "MLB1652"},
    "celular": {"query": "celular smartphone", "label": "Celulares", "category_id": "MLB1055"},
    "tablet": {"query": "tablet", "label": "Tablets", "category_id": "MLB1118"},
    "smart_tv": {"query": "smart tv 4k", "label": "Smart TVs", "category_id": "MLB1002"},
    "fone": {"query": "fone de ouvido bluetooth", "label": "Fones de Ouvido", "category_id": "MLB1051"},
    "ssd": {"query": "ssd nvme interno", "label": "SSDs", "category_id": "MLB1700"},
    "placa_video": {"query": "placa de video nvidia rtx", "label": "Placas de Vídeo", "category_id": "MLB1701"},
    "console": {"query": "console playstation xbox", "label": "Consoles", "category_id": "MLB1144"},
    "monitor": {"query": "monitor gamer 144hz", "label": "Monitores", "category_id": "MLB1006"},
    "mouse": {"query": "mouse gamer sem fio", "label": "Mouses Gamer", "category_id": "MLB1034"},
    "teclado": {"query": "teclado gamer mecanico", "label": "Teclados Gamer", "category_id": "MLB1033"},
    "impressora": {"query": "impressora multifuncional", "label": "Impressoras", "category_id": "MLB1009"},
}

ML_SEARCH_API = "https://api.mercadolibre.com/sites/MLB/search"

# affiliate link format: product link + client tracking params
ML_AFFILIATE_PARAMS = "matt_tool=affiliate&matt_word=&matt_source=&matt_campaign=&client_id={client_id}"

# browser-like headers shared by both strategies
_BROWSER_HEADERS = {
    "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept-Encoding": "gzip, deflate, br",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
}


@dataclass
class MLOffer:
    title: str
    price: float
    old_price: float | None
    discount_percent: float
    image_url: str
    affiliate_link: str
    category: str
    installment_text: str = ""
    pix_discount_text: str = ""


# ── in-memory cache ───────────────────────────────────────────────────────
_ml_cache: dict[str, dict] = {}
CACHE_TTL_MINUTES = 60  # 1h cache


class MercadoLivreGateway:
    """
    fetches electronics products from ml.
    tries the public API first; if blocked (403), falls back to web scraping.
    """

    def __init__(self, profile_slug: str = "", client_id: str = ""):
        self.profile_slug = profile_slug
        self.client_id = client_id.strip() if client_id else ""
        self.profile_url = f"https://www.mercadolivre.com.br/social/{profile_slug}/lists" if profile_slug else ""

    def _build_affiliate_link(self, product_url: str) -> str:
        """appends affiliate tracking params to a ml product url."""
        if not product_url:
            return product_url
        
        import urllib.parse
        parsed = urllib.parse.urlparse(product_url)
        query = dict(urllib.parse.parse_qsl(parsed.query))
        
        # remove old matt_ parameters to avoid conflicts
        keys_to_remove = [k for k in query.keys() if k.startswith("matt_")]
        for k in keys_to_remove:
            del query[k]
        
        if self.client_id:
            query["matt_tool"] = self.client_id
            if self.profile_slug:
                query["matt_word"] = self.profile_slug
            query["matt_source"] = "social"
            query["matt_campaign"] = ""
            query["forceInApp"] = "true"
        
        new_query = urllib.parse.urlencode(query)
        parsed = parsed._replace(query=new_query)
        return urllib.parse.urlunparse(parsed)

    async def get_offers(
        self,
        categories: list[str] | None = None,
        min_discount_percent: float = 5.0,
        max_offers: int = 5,
        custom_search_terms: str = "",
        preferred_brands: str = "",
    ) -> list[MLOffer]:
        """returns affiliate offers from ml."""
        if not categories:
            categories = []

        cache_key = f"{','.join(sorted(categories))}:{custom_search_terms}:{preferred_brands}:{self.client_id}"
        now = datetime.utcnow()

        if cache_key in _ml_cache:
            cached = _ml_cache[cache_key]
            if cached["expires"] > now:
                logger.info("[ml] serving %d offers from cache", len(cached["offers"]))
                filtered = [o for o in cached["offers"] if o.discount_percent >= min_discount_percent]
                return filtered[:max_offers]

        all_offers: list[MLOffer] = []
        brands = [b.strip() for b in preferred_brands.split(",") if b.strip()] if preferred_brands else []
        
        search_terms = []
        if custom_search_terms:
            search_terms.extend([t.strip() for t in custom_search_terms.split(",") if t.strip()])
        else:
            for cat in categories:
                if cat in ML_CATEGORY_MAP:
                    if brands:
                        for brand in brands:
                            search_terms.append(f"{cat} {brand}")
                    else:
                        search_terms.append(cat)
            
        if not search_terms:
            return []

        per_category = max(2, max_offers // max(len(search_terms), 1))

        tasks = [
            self._fetch_category(term, per_category * 3)
            for term in search_terms
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        for result in results:
            if isinstance(result, list):
                all_offers.extend(result)
            elif isinstance(result, Exception):
                logger.warning("[ml] category fetch error: %s", result)

        # sort by discount descending, deduplicate by title
        all_offers.sort(key=lambda o: o.discount_percent, reverse=True)
        seen_titles: set[str] = set()
        unique_offers: list[MLOffer] = []
        for o in all_offers:
            if brands and not any(b.lower() in o.title.lower() for b in brands):
                continue
            
            key = o.title[:50].lower()
            if key not in seen_titles:
                seen_titles.add(key)
                unique_offers.append(o)

        # ONLY cache if we got results — never cache empty results
        if unique_offers:
            _ml_cache[cache_key] = {
                "expires": now + timedelta(minutes=CACHE_TTL_MINUTES),
                "offers": unique_offers,
            }

        logger.info(
            "[ml] fetched %d total offers across %d categories (cached for %dmin)",
            len(unique_offers), len(categories), CACHE_TTL_MINUTES if unique_offers else 0,
        )

        filtered = [o for o in unique_offers if o.discount_percent >= min_discount_percent]
        return filtered[:max_offers]

    async def _fetch_category(self, category_key: str, limit: int = 10) -> list[MLOffer]:
        """fetches products. tries API first, falls back to web scrape on 403."""
        # try API first
        offers = await self._fetch_category_api(category_key, limit)
        if offers is not None:
            return offers

        # fallback: scrape website
        logger.info("[ml] API blocked, falling back to web scrape for '%s'", category_key)
        return await self._fetch_category_scrape(category_key, limit)

    # ── strategy 1: public API ───────────────────────────────────────────

    async def _fetch_category_api(self, category_key: str, limit: int = 10) -> list[MLOffer] | None:
        """tries the ml public search API. returns None if blocked (403/429)."""
        cat_info = ML_CATEGORY_MAP.get(category_key, {})
        query = cat_info.get("query", category_key)

        params = {
            "q": query,
            "sort": "relevance",
            "limit": min(limit, 50),
            "condition": "new",
        }

        headers = {
            **_BROWSER_HEADERS,
            "Accept": "application/json, text/plain, */*",
            "Referer": "https://www.mercadolivre.com.br/",
            "Origin": "https://www.mercadolivre.com.br",
        }

        try:
            async with httpx.AsyncClient(timeout=20.0, follow_redirects=True) as client:
                resp = await client.get(ML_SEARCH_API, params=params, headers=headers)

                if resp.status_code in (403, 429):
                    logger.warning("[ml] API returned %s for '%s'", resp.status_code, category_key)
                    return None  # signal to try scraping

                resp.raise_for_status()
                data = resp.json()
        except httpx.HTTPStatusError as e:
            if e.response.status_code in (403, 429):
                return None
            logger.error("[ml] API http error for '%s': %s", category_key, e)
            return []
        except Exception as e:
            logger.error("[ml] API error for '%s': %s", category_key, e)
            return []

        results = data.get("results", [])
        offers = []
        for item in results:
            try:
                offer = self._parse_api_item(item, category_key)
                if offer:
                    offers.append(offer)
            except Exception as e:
                logger.debug("[ml] error parsing api item: %s", e)

        logger.info("[ml] API fetched %d offers for '%s'", len(offers), category_key)
        return offers

    # ── strategy 2: web scraping fallback ─────────────────────────────────

    async def _fetch_category_scrape(self, category_key: str, limit: int = 10) -> list[MLOffer]:
        """scrapes ml search results page simulating Googlebot to bypass captchas/login walls."""
        cat_info = ML_CATEGORY_MAP.get(category_key, {})
        query = cat_info.get("query", category_key)
        search_slug = query.replace(" ", "-")

        url = f"https://lista.mercadolivre.com.br/{search_slug}_Condition_2230284_NoIndex_True"

        # Pretend to be Googlebot to bypass login wall and get server-rendered HTML
        headers = {
            "User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Cache-Control": "no-cache"
        }

        try:
            async with httpx.AsyncClient(timeout=25.0, follow_redirects=True) as client:
                resp = await client.get(url, headers=headers)
                resp.raise_for_status()
                html = resp.text
        except Exception as e:
            logger.error("[ml] scrape fetch error for '%s': %s", category_key, e)
            return []

        soup = BeautifulSoup(html, "html.parser")
        items = soup.select(".ui-search-result__wrapper")

        if not items:
            logger.warning("[ml] no product wrappers found for '%s' (page len=%d)", category_key, len(html))
            return []

        offers = []
        for item in items[:limit]:
            try:
                title_node = item.select_one("h3.poly-component__title-wrapper a, h2.ui-search-item__title, a.poly-component__title")
                if not title_node:
                    continue
                
                title = title_node.text.strip()
                if not title or len(title) < 5:
                    continue

                link = title_node.get("href", "")
                affiliate_link = self._build_affiliate_link(link)

                price_node = item.select_one(".poly-price__current .andes-money-amount__fraction, .ui-search-price__second-line .andes-money-amount__fraction")
                if not price_node:
                    continue
                price_str = price_node.text.replace(".", "").replace(",", ".")
                price = float(price_str)

                # discount
                discount_node = item.select_one(".poly-price__disc_label, .ui-search-price__discount")
                discount = 0.0
                if discount_node:
                    m = re.search(r'(\d+)%', discount_node.text)
                    if m:
                        discount = float(m.group(1))

                old_price = None
                if discount > 0:
                    old_price_node = item.select_one("s.andes-money-amount--previous .andes-money-amount__fraction")
                    if old_price_node:
                        old_price_str = old_price_node.text.replace(".", "").replace(",", ".")
                        old_price = float(old_price_str)
                    else:
                        old_price = round(price / (1 - (discount / 100.0)), 2)

                img_node = item.select_one("img.poly-component__picture, img.ui-search-result-image__element")
                if not img_node:
                    continue
                img_url = img_node.get("src") or img_node.get("data-src") or ""
                
                installment_text = ""
                install_node = item.select_one(".poly-price__installments")
                if install_node:
                    installment_text = " ".join(install_node.stripped_strings)

                if len(title) > 100:
                    title = title[:97] + "..."

                offers.append(MLOffer(
                    title=title,
                    price=price,
                    old_price=old_price,
                    discount_percent=discount,
                    image_url=img_url,
                    affiliate_link=affiliate_link,
                    category=category_key,
                    installment_text=installment_text,
                    pix_discount_text=""
                ))
            except Exception as e:
                logger.debug("[ml] error parsing scraped item: %s", e)

        logger.info("[ml] scraped %d offers for '%s'", len(offers), category_key)
        return offers

    # ── shared item parser ────────────────────────────────────────────────

    def _parse_api_item(self, item: dict, category_key: str) -> MLOffer | None:
        """parses a single ml search result (from API or __NEXT_DATA__) into an MLOffer."""
        title = item.get("title", "").strip()
        if not title or len(title) < 5:
            return None

        price = float(item.get("price", 0) or 0)
        original_price = float(item.get("original_price") or 0)

        if price <= 0:
            return None

        discount = 0.0
        if original_price and original_price > price:
            discount = round((1 - price / original_price) * 100, 1)

        thumbnail = (
            item.get("thumbnail", "")
            .replace("http://", "https://")
            .replace("-I.jpg", "-O.jpg")
        )

        permalink = item.get("permalink", "")
        affiliate_link = self._build_affiliate_link(permalink)

        installment_text = ""
        installments = item.get("installments")
        if installments and isinstance(installments, dict):
            qty = installments.get("quantity")
            amount = installments.get("amount")
            rate = installments.get("rate", 0)
            if qty and amount:
                price_fmt = f"R$ {amount:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
                sem_juros = " sem juros" if rate == 0 else ""
                installment_text = f"{qty}x de {price_fmt}{sem_juros}"

        if len(title) > 100:
            title = title[:97] + "..."

        return MLOffer(
            title=title,
            price=price,
            old_price=original_price if original_price > price else None,
            discount_percent=discount,
            image_url=thumbnail,
            affiliate_link=affiliate_link,
            category=category_key,
            installment_text=installment_text,
            pix_discount_text="",
        )

    @staticmethod
    def get_available_categories() -> dict[str, str]:
        """returns available category keys and labels."""
        return {k: v["label"] for k, v in ML_CATEGORY_MAP.items()}
