# Generated by Django 5.2.1 on 2025-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Your Google Gemini API Key', max_length=255, null=True),
        ),
    ]
