# Generated by Django 5.2.1 on 2025-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_whatsappconfig_gemini_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconfig',
            name='instance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
