# Generated by Django 5.2.1 on 2025-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_whatsappconfig_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini')], default='gemini', help_text='Select the AI provider (Only Gemini supported currently)', max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key for the selected provider', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one AI configuration can be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.RemoveField(
            model_name='whatsappconfig',
            name='gemini_api_key',
        ),
    ]
