# Generated by Django 5.2.1 on 2025-06-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bulkcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='persona_prompt',
            field=models.TextField(blank=True, help_text="Define the AI's persona or system prompt (e.g., 'You are a helpful clothing sales assistant specializing in summer wear.')", null=True),
        ),
    ]
