# Generated by Django 5.2.1 on 2025-06-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aiconfig_persona_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='persona_prompt',
            field=models.TextField(blank=True, help_text='Define como a IA deve se comportar especificamente com este contato. Se preenchido, sobrescreve a persona geral da IA.', null=True),
        ),
    ]
