# Generated by Django 5.1.3 on 2024-12-17 contextual_ai_features

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contact_persona_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sentiment', models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('very_negative', 'Very Negative'), ('frustrated', 'Frustrated'), ('excited', 'Excited'), ('confused', 'Confused')], default='neutral', max_length=20)),
                ('sentiment_confidence', models.FloatField(default=0.0)),
                ('sentiment_history', models.JSONField(default=list)),
                ('technical_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('technical_confidence', models.FloatField(default=0.0)),
                ('technical_indicators', models.JSONField(default=dict)),
                ('funnel_stage', models.CharField(choices=[('awareness', 'Awareness'), ('interest', 'Interest'), ('consideration', 'Consideration'), ('intent', 'Intent'), ('evaluation', 'Evaluation'), ('purchase', 'Purchase'), ('retention', 'Retention')], default='awareness', max_length=20)),
                ('funnel_confidence', models.FloatField(default=0.0)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('conversation_topics', models.JSONField(default=list)),
                ('needs_persona_adaptation', models.BooleanField(default=False)),
                ('last_adaptation_trigger', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('context_type', models.CharField(choices=[('sentiment', 'Sentiment Based'), ('technical', 'Technical Level'), ('funnel', 'Sales Funnel'), ('industry', 'Industry Specific'), ('time_of_day', 'Time of Day'), ('urgency', 'Urgency Level')], max_length=20)),
                ('context_value', models.CharField(max_length=50)),
                ('persona_prompt', models.TextField()),
                ('tone_adjustments', models.JSONField(default=dict)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('effectiveness_rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('context_type', 'context_value')},
            },
        ),
        migrations.CreateModel(
            name='PersonaAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptation_type', models.CharField(choices=[('sentiment_based', 'Sentiment Based'), ('technical_level', 'Technical Level'), ('funnel_stage', 'Sales Funnel Stage'), ('conversation_pattern', 'Conversation Pattern'), ('manual_override', 'Manual Override')], max_length=30)),
                ('original_persona', models.TextField()),
                ('adapted_persona', models.TextField()),
                ('trigger_reason', models.CharField(max_length=200)),
                ('adaptation_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('effectiveness_score', models.FloatField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_adaptations', to='core.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_confidence', models.FloatField()),
                ('sentiment_keywords', models.JSONField(default=list)),
                ('technical_terms', models.JSONField(default=list)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('detected_intent', models.CharField(blank=True, max_length=100)),
                ('intent_confidence', models.FloatField(default=0.0)),
                ('main_topics', models.JSONField(default=list)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('analysis_version', models.CharField(default='1.0', max_length=10)),
                ('processing_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='core.message')),
            ],
        ),
        migrations.CreateModel(
            name='AdaptationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_persona_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personatemplate')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
    ]

