# Generated by Django 5.2.1 on 2025-06-21 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contextual_ai_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('product_interest', 'Product Interest'), ('price_inquiry', 'Price Inquiry'), ('comparison_shopping', 'Comparison Shopping'), ('repeat_customer', 'Repeat Customer'), ('referral_potential', 'Referral Potential'), ('seasonal_opportunity', 'Seasonal Opportunity'), ('abandoned_cart', 'Abandoned Cart'), ('engagement_drop', 'Engagement Drop')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('pending_action', 'Pending Action'), ('action_taken', 'Action Taken'), ('converted', 'Converted'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='identified', max_length=20)),
                ('confidence_score', models.FloatField(help_text='AI confidence in this opportunity (0-1)')),
                ('trigger_data', models.JSONField(default=dict, help_text='Data that triggered this opportunity')),
                ('analysis_summary', models.TextField(help_text='AI-generated summary of the opportunity')),
                ('suggested_action', models.TextField(help_text='AI-suggested action to take')),
                ('suggested_message', models.TextField(blank=True, help_text='AI-suggested message to send')),
                ('optimal_timing', models.DateTimeField(help_text='Best time to take action')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this opportunity expires')),
                ('conversion_achieved', models.BooleanField(default=False)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='1-5 rating of opportunity quality', null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_opportunities', to='core.contact')),
                ('related_products', models.ManyToManyField(blank=True, to='core.product')),
            ],
            options={
                'ordering': ['-priority', '-confidence_score', '-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0, help_text='Based on message frequency and quality')),
                ('interest_score', models.FloatField(default=0.0, help_text='Based on product inquiries and browsing')),
                ('purchase_intent_score', models.FloatField(default=0.0, help_text='Based on buying signals')),
                ('timing_score', models.FloatField(default=0.0, help_text='Based on optimal timing patterns')),
                ('overall_score', models.FloatField(default=0.0, help_text='Weighted combination of all scores')),
                ('conversion_probability', models.FloatField(default=0.0, help_text='Predicted probability of conversion')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(default='1.0', max_length=10)),
                ('factors_considered', models.JSONField(default=list, help_text='List of factors used in calculation')),
                ('score_trend', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('trend_strength', models.FloatField(default=0.0, help_text='Strength of the trend (0-1)')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_score', to='core.contact')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('follow_up_message', 'Follow-up Message'), ('product_recommendation', 'Product Recommendation'), ('price_alert', 'Price Alert'), ('seasonal_promotion', 'Seasonal Promotion'), ('engagement_recovery', 'Engagement Recovery'), ('cross_sell', 'Cross-sell'), ('upsell', 'Upsell'), ('referral_request', 'Referral Request')], max_length=30)),
                ('message_sent', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_delivered', models.BooleanField(default=False)),
                ('message_read', models.BooleanField(default=False)),
                ('response_received', models.BooleanField(default=False)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, help_text='0-1 score of engagement quality', null=True)),
                ('conversion_achieved', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.leadopportunity')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('seasonal', 'Seasonal Campaign'), ('product_launch', 'Product Launch'), ('re_engagement', 'Re-engagement'), ('cross_sell', 'Cross-sell'), ('win_back', 'Win-back'), ('referral', 'Referral')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_segments', models.JSONField(default=list, help_text='Customer segments to target')),
                ('min_lead_score', models.FloatField(default=0.0, help_text='Minimum lead score to include')),
                ('max_contacts', models.IntegerField(blank=True, help_text='Maximum contacts to include', null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('optimal_send_hours', models.JSONField(default=list, help_text='Preferred hours to send messages')),
                ('message_templates', models.JSONField(default=list, help_text='List of message templates')),
                ('contacts_targeted', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('responses_received', models.IntegerField(default=0)),
                ('conversions_achieved', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('products_to_promote', models.ManyToManyField(blank=True, to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('time_based', 'Time-based'), ('behavior_based', 'Behavior-based'), ('event_based', 'Event-based'), ('pattern_based', 'Pattern-based'), ('external_trigger', 'External Trigger')], max_length=20)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='Conditions that trigger this rule')),
                ('action_template', models.TextField(help_text='Template for the action to take')),
                ('message_template', models.TextField(help_text='Template for the message to send')),
                ('target_customer_segments', models.JSONField(default=list, help_text='Customer segments this rule applies to')),
                ('min_interval_hours', models.IntegerField(default=24, help_text='Minimum hours between applications')),
                ('max_applications_per_customer', models.IntegerField(default=3, help_text='Max times to apply per customer')),
                ('optimal_hours', models.JSONField(default=list, help_text='Optimal hours of day to apply (0-23)')),
                ('times_triggered', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate (0-1)')),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_categories', models.ManyToManyField(blank=True, to='core.product')),
            ],
            options={
                'ordering': ['-success_rate', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBehaviorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('browsing_pattern', 'Browsing Pattern'), ('purchase_timing', 'Purchase Timing'), ('price_sensitivity', 'Price Sensitivity'), ('communication_preference', 'Communication Preference'), ('product_affinity', 'Product Affinity'), ('seasonal_behavior', 'Seasonal Behavior'), ('engagement_cycle', 'Engagement Cycle')], max_length=30)),
                ('pattern_data', models.JSONField(default=dict)),
                ('confidence_level', models.FloatField(help_text='Confidence in this pattern (0-1)')),
                ('sample_size', models.IntegerField(help_text='Number of data points used')),
                ('first_observed', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_predicted_action', models.DateTimeField(blank=True, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, help_text='Accuracy of predictions based on this pattern', null=True)),
                ('times_validated', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_patterns', to='core.contact')),
            ],
            options={
                'ordering': ['-confidence_level', '-last_updated'],
                'unique_together': {('contact', 'pattern_type')},
            },
        ),
        migrations.AddIndex(
            model_name='leadopportunity',
            index=models.Index(fields=['status', 'priority'], name='core_leadop_status_290286_idx'),
        ),
        migrations.AddIndex(
            model_name='leadopportunity',
            index=models.Index(fields=['contact', 'status'], name='core_leadop_contact_4d91e8_idx'),
        ),
        migrations.AddIndex(
            model_name='leadopportunity',
            index=models.Index(fields=['optimal_timing'], name='core_leadop_optimal_c4d153_idx'),
        ),
    ]
