# Generated by Django 5.1.3 on 2025-06-30 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_commandpattern_safetyrule_commandanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Número no formato: +5511999999999', max_length=20)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('qr_waiting', 'Aguardando QR Code'), ('connected', 'Conectado'), ('error', 'Erro')], default='disconnected', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='QR Code para conexão', null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_messages_per_hour', models.IntegerField(default=100, help_text='Limite de mensagens por hora')),
                ('min_interval_seconds', models.IntegerField(default=2, help_text='Intervalo mínimo entre mensagens')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão WhatsApp',
                'verbose_name_plural': 'Conexões WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('participants_count', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.whatsappconnection')),
            ],
            options={
                'verbose_name': 'Grupo WhatsApp',
                'verbose_name_plural': 'Grupos WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.whatsappconnection')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-sent_at'],
            },
        ),
    ]
